### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by jasmineortega** [UBC-MDS/ImgHelpR#31]
Peer Review: 
- [x] [Initiate package review in R](https://github.com/UBC-MDS/software-review-2022/issues/15)
- [x] [Initiate package review in Python](https://github.com/UBC-MDS/software-review-2022/issues/17)

GitHub actions workflow for CI (steven)
- [x] Check-standard 
- [x] Test-coverage 

Documentation:
- [x] vignette (Jasmine)
- [x] pkgdown (Jasmine)
- [x] License [discussion](https://github.com/UBC-MDS/ImgHelpR/issues/32)
