### ISSUE TITLE
Week 2 Checklist

### ISSUE THREAD

**Issue by jasmineortega** [UBC-MDS/ImgHelpR#4]
Project Structure:
- [x] Create repo
- [x] MIT license
- [x] code of conduct
- [x] DESCRIPTION file
- [x] CONTRIBUTING.md
- [x] README.Rmd

Function Documentation:
- [x] Crop Function Documentation
- [x] Color Conversion Function Documentation
- [x] Rotate Function Documentation
- [x]  Compress Function Documentation

**Comment by jasmineortega** [comment]
To bring up in meeting tomorrow: 
- [x] are the R function descriptions in README.Rmd ok?
- [x] missing CONTRIBUTING.md (`usethis::use_tidy_contributing() `)
- [x] empty functions
